/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      animation: {
        in: 'in 0.2s ease-out',
        'fade-in': 'fade-in 0.2s ease-out',
        'slide-in-from-top-4': 'slide-in-from-top-4 0.2s ease-out',
      },
      keyframes: {
        in: {
          '0%': { opacity: '0', transform: 'translateY(-8px) scale(0.98)' },
          '100%': { opacity: '1', transform: 'translateY(0) scale(1)' },
        },
        'fade-in': {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        'slide-in-from-top-4': {
          '0%': { transform: 'translateY(-16px)' },
          '100%': { transform: 'translateY(0)' },
        },
      },
    },
  },
  safelist: [
    'fixed',
    'inset-0',
    'z-[999999]',
    'flex',
    'items-start',
    'items-center',
    'justify-center',
    'justify-between',
    'bg-black/50',
    'mt-20',
    'w-full',
    'w-4',
    'h-4',
    'max-w-2xl',
    'rounded-lg',
    'bg-base-100',
    'bg-base-200',
    'shadow-2xl',
    'p-4',
    'px-4',
    'py-2',
    'py-3',
    'input',
    'input-bordered',
    'text-lg',
    'text-sm',
    'text-xs',
    'text-center',
    'text-base-content/60',
    'max-h-96',
    'overflow-y-auto',
    'cursor-pointer',
    'gap-3',
    'hover:bg-base-200',
    'min-w-0',
    'flex-1',
    'truncate',
    'font-medium',
    'kbd',
    'kbd-xs',
    'mx-1',
    'mx-2',
    'border-t',
    'border-base-300',
  ],
  // eslint-disable-next-line import/no-unresolved, global-require
  plugins: [require('daisyui')],
  daisyui: {
    themes: ['light', 'dark'],
  },
};
